# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-11 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20191009_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfav',
            options={'ordering': ['id'], 'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
        migrations.AlterModelOptions(
            name='uservote',
            options={'ordering': ['id'], 'verbose_name': '用户投票', 'verbose_name_plural': '用户投票'},
        ),
    ]
