# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-20 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reproduce_source',
            field=models.URLField(blank=True, help_text='转载来源地址', max_length=256, null=True, verbose_name='转载来源地址'),
        ),
    ]
