# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-23 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190920_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reproduce_source',
            field=models.URLField(blank=True, help_text='转载来源地址', max_length=512, null=True, verbose_name='转载来源地址'),
        ),
    ]
