# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-23 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190923_0126'),
        ('blog', '0003_auto_20190923_0109'),
    ]

    operations = [
    ]
