# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-04 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20190923_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(help_text='文章分类', on_delete=django.db.models.deletion.CASCADE, related_name='cat_post', to='blog.Category', verbose_name='分类'),
        ),
    ]
