# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191004_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upvote_count',
            field=models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数'),
        ),
    ]
