# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-24 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191011_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=124, verbose_name='slug'),
        ),
    ]
