# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191107_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ifshow',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
