# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-21 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import fileserver.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostImg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='文件名', max_length=64, verbose_name='文件名')),
                ('imgMd5', models.CharField(max_length=128, verbose_name='MD5值')),
                ('img', models.ImageField(help_text='图片', upload_to=fileserver.models.img_directory_path, verbose_name='图片')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
