# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-07 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimg',
            options={'verbose_name': '文章图片', 'verbose_name_plural': '文章图片'},
        ),
    ]
