# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-13 20:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, help_text='正文', null=True, verbose_name='正文'),
        ),
    ]
