# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-07 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20191107_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='urltag',
            field=models.CharField(help_text='标签', max_length=32, unique=True, verbose_name='标签'),
        ),
    ]
