# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-08 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20191107_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order', 'id'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id', 'create_date'], 'verbose_name': '主题', 'verbose_name_plural': '主题'},
        ),
        migrations.AddField(
            model_name='topic',
            name='codestyle',
            field=models.CharField(blank=True, default='monokai', help_text='代码风格', max_length=24, null=True, verbose_name='代码风格'),
        ),
    ]
