# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-09 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20191108_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='ifshow',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
