# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-10 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_topic_ifshow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['reproduce', 'id', 'create_date'], 'verbose_name': '主题', 'verbose_name_plural': '主题'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(help_text='标题', max_length=64, verbose_name='标题'),
        ),
    ]
