# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-07 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20191014_0342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id'], 'verbose_name': '反馈消息', 'verbose_name_plural': '反馈消息'},
        ),
    ]
